SET SERVEROUT ON
DECLARE
    NOMBRE VARCHAR2(20);
    APELLIDO1 VARCHAR2(20);
    APELLIDO2 VARCHAR2(20);
BEGIN
    NOMBRE:='andres';
    APELLIDO1:='LEMUS';
    APELLIDO2:='Deleon';
    DBMS_OUTPUT.PUT_LINE(UPPER(SUBSTR(NOMBRE,1,1))||'.'||UPPER(SUBSTR(APELLIDO1,1,1))||'.'||UPPER(SUBSTR(APELLIDO2,1,1)));
    DBMS_OUTPUT.PUT_LINE(to_char(date'2001-04-30', 'DAY'));
END;