SET SERVEROUT ON
DECLARE
    IMP CONSTANT NUMBER := 0.21;
    PRECIO NUMBER(5,2);
    VALOR PRECIO%TYPE;
BEGIN
    PRECIO := 59.99;
    VALOR := PRECIO * IMP;
    DBMS_OUTPUT.PUT_LINE(VALOR);
END;