SET SERVEROUT ON
DECLARE
    SALARIO NUMBER;
    NOMBRE employees.first_name%TYPE;
    EMPLEADO EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO EMPLEADO FROM EMPLOYEES
    WHERE employee_id = 100;
    DBMS_OUTPUT.put_line(EMPLEADO.SALARY*100);
    DBMS_OUTPUT.put_line(EMPLEADO.FIRST_NAME);
END;