SET SERVEROUT ON
DECLARE
    TYPE DEPARTAMENTOS IS TABLE OF
        DEPARTMENTS.DEPARTMENT_NAME%TYPE
    INDEX BY PLS_INTEGER;
    
    TYPE EMPLEADOS IS TABLE OF
        EMPLOYEES%ROWTYPE
    INDEX BY PLS_INTEGER;
    
    DEPTS DEPARTAMENTOS;
    EMPLES EMPLEADOS;
BEGIN
    DEPTS(1):='INFORMATICA';
    DEPTS(2):='RRHH';
    DBMS_OUTPUT.PUT_LINE(DEPTS(1));
    DBMS_OUTPUT.PUT_LINE(DEPTS(2));
    DBMS_OUTPUT.PUT_LINE(DEPTS.LAST);
    DBMS_OUTPUT.PUT_LINE(DEPTS.FIRST);
    IF DEPTS.EXISTS(3) THEN
        dbms_output.put_line(DEPTS(3));
    ELSE
        dbms_output.put_line('Ese valor no existe');
    END IF;
    
    SELECT * INTO EMPLES(1) FROM EMPLOYEES WHERE employee_id = 100;
    DBMS_OUTPUT.PUT_LINE(EMPLES(1).FIRST_NAME);
END;
/