SET SERVEROUT ON
DECLARE
    TYPE empleado IS RECORD
        (nombre VARCHAR2(100),
        salario NUMBER,
        fecha employees.hire_date%TYPE,
        datos employees%ROWTYPE);
    emple1 empleado;
BEGIN
    SELECT * INTO emple1.datos
    FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
    EMPLE1.NOMBRE:=EMPLE1.DATOS.FIRST_NAME||' '||EMPLE1.DATOS.LAST_NAME;
    EMPLE1.SALARIO:=EMPLE1.DATOS.SALARY*0.80;
    EMPLE1.FECHA:=EMPLE1.DATOS.HIRE_DATE;
    DBMS_OUTPUT.PUT_LINE(EMPLE1.NOMBRE);
    DBMS_OUTPUT.PUT_LINE(EMPLE1.SALARIO);
    DBMS_OUTPUT.PUT_LINE(EMPLE1.FECHA);
    DBMS_OUTPUT.PUT_LINE(EMPLE1.DATOS.FIRST_NAME);
END;